version: "3.9"

services:
 
  postgres:
    container_name: postgres
    image: postgres:15.1
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5432:5432"

  accrual:
    container_name: accrual
    platform: linux/amd64
    env_file:
      - ./.env
    build:
      context: ./..
      dockerfile: deployments/accrual/Dockerfile
    restart: always
    ports:
      - "8081:8081"

networks:
    gophermart:
        name: gophermart