// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto(in *jlexer.Lexer, out *WithdrawalResponseBatch) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(WithdrawalResponseBatch, 0, 1)
			} else {
				*out = WithdrawalResponseBatch{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 WithdrawalResponse
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto(out *jwriter.Writer, in WithdrawalResponseBatch) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawalResponseBatch) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawalResponseBatch) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawalResponseBatch) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawalResponseBatch) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto(l, v)
}
func easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto1(in *jlexer.Lexer, out *WithdrawalResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.OrderID = string(in.String())
		case "sum":
			out.Amount = float64(in.Float64())
		case "processed_at":
			out.CreatedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto1(out *jwriter.Writer, in WithdrawalResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.OrderID))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Amount))
	}
	{
		const prefix string = ",\"processed_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawalResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawalResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawalResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawalResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto1(l, v)
}
func easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto2(in *jlexer.Lexer, out *Withdrawal) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.OrderID = string(in.String())
		case "sum":
			out.Amount = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto2(out *jwriter.Writer, in Withdrawal) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.OrderID))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Amount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Withdrawal) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Withdrawal) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson52c08f61EncodeGithubComPatradenYaPracticumGoMartInternalAppDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Withdrawal) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Withdrawal) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson52c08f61DecodeGithubComPatradenYaPracticumGoMartInternalAppDto2(l, v)
}
